### ISSUE TITLE
Sprite #blah#pulse-big.png is too big 

### ISSUE THREAD

**Issue by DaveInTexas** [ReikaKalseki/Reika_FactorioMods_Issues#11]
full error in the screenshot, I didn't think the full path was necessary in the title

Screenshot:  https://www.dropbox.com/s/ef8ekrhmfx3g5tf/ecc-ERROR.jpg?dl=0

**Comment by DaveInTexas** [comment]
i saw your comment to something someone posted 8 hours ago..  i haven't changed my graphics settings since installing the game but i'll try it :)

**Comment by DaveInTexas** [comment]
these are my settings, it may be a limitation of my video card since i'm using atlas texture size largest possible...  i'm going to tinker, lol.


https://www.dropbox.com/s/uaeapijupczo1xv/Factorio-settings.jpg?dl=0

**Comment by DaveInTexas** [comment]
I turned up sprite resolution (just because, not as part of debugging lol) and turned on texture compression and the error went away.

**Comment by ReikaKalseki** [comment]
I still want to get to the bottom of this. Worst case scenario, have a low-resolution image fallback.

**Comment by DaveInTexas** [comment]
good luck :) 👍

**Comment by kupp11** [comment]
Does anyone have a workaround this? I can't turn up my sprite resolution, don't have a good enough VRAM. Only thing keeping behemoths out of my base is this mod :/

**Comment by DaveInTexas** [comment]
kupp11, did you try turning on compression?

**Comment by randiskhan** [comment]
If you change the three pulse-.png sprite sheets from 1 row of 14 to 2 rows of 7, and change line 293 of dome.lua to "line_length = 7,", the mod loads no error. I believe the problem is the pulse-.png image files are too wide for systems that want a max sprite size of 2048. I haven't tried to use the dome yet to see if this fix breaks any logic.

**Comment by randiskhan** [comment]
![pulse-big](https://user-images.githubusercontent.com/2105769/29253598-ef9981c0-8070-11e7-9c95-322db5011505.png)
![pulse-medium](https://user-images.githubusercontent.com/2105769/29253599-ef9a1626-8070-11e7-8654-d09f3dc05609.png)
![pulse-small](https://user-images.githubusercontent.com/2105769/29253600-ef9a1144-8070-11e7-8209-0f21ee147f56.png)
Here's the updated sprite sheets.

**Comment by randiskhan** [comment]
Crap. I thought that would make download links, sorry.
Save the first one as pulse-big.png, the second as pulse-medium.png, and third as pulse-small.png.

**Comment by Mandarman** [comment]
Where do I save these files to?

**Comment by randiskhan** [comment]
Unzip the mod.
Save the above files to "EndgameCombat_1.0.6\graphics\entity\dome\" replacing the existing ones.
Make the change to dome.lua (in "EndgameCombat_1.0.6\prototypes\").
Re zip the mod and put back in mods directory.

Note: Reika has released v1.0.7 since I made this fix. I don't know if the new version addresses this issue.
Update: I just tried v1.0.7 and it has same error upon load. Instructions are same except change 1.0.6 to 1.0.7 in file paths.
Update 2: v1.0.7 with fix works for me.

**Comment by kupp11** [comment]
Yes, I checked the box next to texture compression but since I can't increase the sprite resolution the error still persists. I'll just wait for a fix. I don't wanna mess something else up by screwing around in the zipped file.

**Comment by Mandarman** [comment]
Yeah, I get a message stating the sprites aren't in the boundaries wit your fix. Followed it exactly and triple checked. Will just wait till the author fixes it.

**Comment by ReikaKalseki** [comment]
I will try low-resolution fallbacks; until then, you can just downscale the images and edit the dome.lua entries accordingly.

**Comment by Mandarman** [comment]
Any ETA on that release? I'm just getting texture error messages if I touch anything.

**Comment by ReikaKalseki** [comment]
I used @randiskhan's 2-rows-of-7 idea, since I cannot fetch user graphics settings (that or noone seems capable of reading my post on the forums before posting unhelpful replies). It should work. Try the new version.
