### ISSUE TITLE
Large FPS/UPS drop with Bioluminescence

### ISSUE THREAD

**Issue by geostar1024** [ReikaKalseki/Reika_FactorioMods_Issues#199]
With the mod enabled, I get ~22 FPS (UPS returns to 60 when looking at the map, for example), which goes back to ~60 when the mod is disabled. I do have quite a few chunks explored (with many glowing trees and biters), which could possibly be part of the problem. If it would be useful, I could upload my save (though it uses other mods, I've verified that the issue still occurs even with every other mod removed except Bioluminescence).

**Comment by ReikaKalseki** [comment]
Does the issue persist if you remove all biters and spawners?

**Comment by geostar1024** [comment]
It persists when all biters are removed, at least; I'll check tomorrow to see if removing the spawners has any effect.

**Comment by ReikaKalseki** [comment]
So...

**Comment by eldorel** [comment]
I'm having the exact same issue on our multiplayer server right now. 
Nuking biters and spawners has no effect.  (even went so far as to install 'bitersbegone' to make sure they weren't loading back in.)

Screenshots with and without: https://imgur.com/a/Xev9R69
Without Bioluminescence, I can run this map at 2x game speed and get 120FPS/120UPS with other mods loaded, but with it enabled I drop to 13 FPS and 13 UPS. (only this mod and the requisite DragonIndustries are loaded.)

We're pretty sure that we weren't seeing the issue prior to upgrading above 17.69, but I can't be 100% on that.  ( We started a new map with 17.69 so that a friend could learn the game solo for a while without messing up our main save).  

If you would like access for testing, I can host the server for you to hop in and have a look or post a copy of the map.  


Edit:  More data

I created a new map with nothing on it, and generated the entire map with this command

/c local radius=10000 game.player.force.chart(game.player.surface, {{x = -radius, y = -radius}, {x = radius, y = radius}})

It took about 10 minutes. 

I then loaded the map from save with and without the mod enabled, and I can hold 120/120 without it, but only 30/60 with. 

This is with no other mods, nothing to keep the rest of the map loaded, and the only active chunks are the ones immediately surrounding the player avatar. 

Enabling "bitersbegone" to disable biters/spawners/etc appears to have no effect.

**Comment by ReikaKalseki** [comment]
Just making sure, you A) do not have retrogen enabled and B) waited for worldgen to finish *completely* (not just the visible part of the map)?

Bioluminescence has worldgen code, though it should be nowhere near expensive enough to account for this.

**Comment by eldorel** [comment]
Retrogen is not enabled, I loaded up the map with the mod enabled to generate, and left it sitting for quite a while tonight to verify that the gen was complete just in case I am misunderstanding how the game loads in areas.

The command I pasted above generated the entire map one chunk at a time in a spiral and the generated area is actually larger than the map itself so you can see it hit the edge of the world. 

Same results tonight. With the mod i'm getting about 30fps/ups, and without it I get 120/120.

**Comment by ReikaKalseki** [comment]
I figured out what is wrong: https://forums.factorio.com/viewtopic.php?f=7&t=85885&p=498230#p498230

In the next version, Biolum has a command to regenerate its lights, which fixes the lag. It also forcibly does it on version update.

I do hope they fix the underlying bug too.
