### ISSUE TITLE
Fucking error after 30 minutes game play

### ISSUE THREAD

**Issue by black199755** [ReikaKalseki/Reika_FactorioMods_Issues#207]
![Capture](https://user-images.githubusercontent.com/54862179/64199356-353db500-ce9b-11e9-9812-0012f6135808.PNG)

**Comment by PaladinFallen** [comment]
First of all, calm the fuck down and read the [Guidelines](https://github.com/ReikaKalseki/Reika_FactorioMods_Issues/blob/master/CONTRIBUTING.md). New updates will cause bugs and crashes.

Second, instead of complaining why not try and solve the problem and help the modder out?

Third, to temporarily fix the issue all you have to do is change the line 436 of the turbine.lua from "__base__" to "__Geothermal__"

**Comment by ReikaKalseki** [comment]
Fixed.
