### ISSUE TITLE
Geothermal - LuaTile API call when LuaTile was invalid.

### ISSUE THREAD

**Issue by Nassiel** [ReikaKalseki/Reika_FactorioMods_Issues#281]
Hi,

While using the Factorio 1.0, final release I see this error. You mod is in the 1.18.15. Any extra information that you'd need, please let me know.

Thanks!

```
LuaTile API call when LuaTile was invalid.
stack traceback:
	__Geothermal__/control.lua:174: in function 'getSpawnData'
	__Geothermal__/control.lua:217: in function 'controlChunk'
	__Geothermal__/control.lua:237: in function <__Geothermal__/control.lua:236>
stack traceback:
	[C]: in function '__index'
	__Geothermal__/control.lua:174: in function 'getSpawnData'
	__Geothermal__/control.lua:217: in function 'controlChunk'
	__Geothermal__/control.lua:237: in function <__Geothermal__/control.lua:236>

```

**Comment by ReikaKalseki** [comment]
What mods do you have that change tiles in the world?

**Comment by numbernegative** [comment]
Also receiving identical error. But only on starting a new game. Adding geothermal to a save already started and loading does not reproduce.
Mods that I know change tiles I also have loaded: Krastorio2, Alien Biomes, Space Exploration.

**Comment by ReikaKalseki** [comment]
It is not AlienBiomes - I use that myself - but does it persist if any of those are removed?

**Comment by Nassiel** [comment]
I have Alien Biomes and Alien Biomes HD.

**Comment by ReikaKalseki** [comment]
So do I.

**Comment by 1avek1** [comment]
I have the same problem.

It happens with BlueprintLab_design_1.0.1 mod when I push the "switch to lab" button. As soon as the Blueprint Lab surface appears, Geothermal crashes the game.

But the problem is not related to any other mods but Geothermal itself. There's a general rule: if Factorio returns some object with .valid field set to false, that object may not be used by mods. The crashing line in Geothermal is:
`if set[tile.name] then`

It's clear that is doesn't check the previous `surface.get_tile` result. The code must be instead:
`if tile and tile.valid and set[tile.name] then`

When I patch it in this way, the problem with Blueprint Lab special surface is solved - no crash anymore. I haven't yet checked how the rest of Geothermal works with it, though.

**Comment by ReikaKalseki** [comment]
This has been fixed.
