### ISSUE TITLE
Issue Loading Endgame Combat

### ISSUE THREAD

**Issue by TankMan4563** [ReikaKalseki/Reika_FactorioMods_Issues#382]
Recently I've started getting this message when trying to start my game:

Failed to load mods: _ _ EndgameCombat _ _ /prototypes/overrides.lua:95: attempt to index field 'burner' (a nil value)
stack traceback:
_ _ EndgameCombat _ _ /prototypes/overrides.lua:95: in main chunk
[C] in function 'require'
_ _ EndgameCombat _ _ /data-updates.lua:6: in main chunk

![Screenshot 2022-07-11 102521](https://user-images.githubusercontent.com/109092900/178299835-8d148980-b349-4c62-994b-161e6bbf5222.png)

**Comment by mmfrnt** [comment]
Updated my mods this morning and I'm getting the same error now.  Very frustrating since it's on a 100+ hour world.  Hope it gets fixed soon.  -_-   _edit: I've narrowed mine down to an issue with Space Exploration.  Tried to revert to an older version of SE with no luck... guess this mod gets uninstalled and I lose my world._

**Comment by CasperTSG** [comment]
I had this same problem. For some reason the train collision function in said file references an array or property that isn't there due to other mods installed. Commenting out the function does get the mod to run again but who knows how stable it is. It hasn't caused any problems for me yet.

**Comment by SomaTGW** [comment]
Having this same issue. I did some poking around and as mmfrnt said, it's Space Exploration, not any required mods, it's Space Exploration itself.

**Comment by ReikaKalseki** [comment]
#285 #381
