### ISSUE TITLE
Oreverhaul [BUG] alien bases spawning way too far from spawn

### ISSUE THREAD

**Issue by Milkman68** [ReikaKalseki/Reika_FactorioMods_Issues#68]
@ReikaKalsek i  installed orverhaul went into the config then turned
redoSpawnerPlacement to false then this happened.
![capture 11](https://user-images.githubusercontent.com/31172185/40572498-d89c5100-6062-11e8-9e4b-34baf6ebb0ff.PNG)
[Blue circle represents spawn point]
is this a bug or did i do something wrong'
because i did tamper with the setting before i figured"
out that i could turn off oreverhaul spawner generation
entirely.

**Comment by ReikaKalseki** [comment]
Turning off the config does not completely remove Oreverhaul's effect, it only limits it (ie it only acts to delete or modify spawners placed by the vanilla code, rather than handling all placement itself). And in doing so makes it very vulnerable to the native Factorio worldgen RNG.

Also, there is a config to control spawner distance multipliers.
